### ISSUE TITLE
JIO WORKING METHOD 1

### ISSUE THREAD

**Issue by DeekshithVelmula** [DeekshithVelmula/plugin.video.jiotv#1]
Use the below zip file using latest kodi version app
[plugin.video.jiotv-2.0.41.zip](https://github.com/user-attachments/files/16401258/plugin.video.jiotv-2.0.41.zip)

**Comment by DeekshithVelmula** [comment]
@Aserguy
@srinu1015
@sahaanup65
@giridathac
@piscesbangalore
@GTTech2305
@nixnotwin
@ranjeets9
@KEERTHI1988-K2
@Akil0189
@nixnotwin

**Comment by piscesbangalore** [comment]
> Use the below zip file using latest kodi version app Uploading plugin.video.jiotv-2.0.41.zip…

No file to download. I think the 3 dots after .zip need to be removed. Not sure.
Does password option work with this?

**Comment by DeekshithVelmula** [comment]
> > Use the below zip file using latest kodi version app Uploading plugin.video.jiotv-2.0.41.zip…
> 
> No file to download. I think the 3 dots after .zip need to be removed. Not sure. Does password option work with this?

I have updated comment. Now download

**Comment by nixnotwin** [comment]
Not working for for non jiotv plus user. Does it require jiotv plus subscription?

**Comment by DeekshithVelmula** [comment]
> Not working for for non jiotv plus user. Does it require jiotv plus subscription?

You should be jio sim user. No subscription required

**Comment by nixnotwin** [comment]
> > Not working for for non jiotv plus user. Does it require jiotv plus subscription?
> 
> You should be jio sim user. No subscription required

Thank you for your wonderful work. I'm using jio sim.

**Comment by giridathac** [comment]
It's working fine with latest Kodi v21 latest development build. I couldn't launch it through add ons though but IPTV working fantastic. I am on firetv stick 4K. Do you also see the issue if launched from addons(genre works but languages doesn't)??

Thank you.  

PS:  Do you need any help in looking at the code?

**Comment by KEERTHI1988-K2** [comment]
Not working again and again, please give permanent solution @DeekshithVelmula

**Comment by giridathac** [comment]
Yes, not working..

**Comment by srinu1015** [comment]
@DeekshithVelmula , it worked yesterday night, but stopped working now. Can you please check and help

**Comment by giridathac** [comment]
Do we have an updated zip?
