### ISSUE TITLE
JIO WORKING METHOD 2

### ISSUE THREAD

**Issue by DeekshithVelmula** [DeekshithVelmula/plugin.video.jiotv#2]
Below  zip file with latest kodi version
[plugin.video.jiotv-2.0.41.zip](https://github.com/user-attachments/files/16436644/plugin.video.jiotv-2.0.41.zip)

**Comment by sahaanup65** [comment]
> Below zip file with latest kodi version [plugin.video.jiotv-2.0.41.zip](https://github.com/user-attachments/files/16436644/plugin.video.jiotv-2.0.41.zip)

Other Channels working but Sony channels are not working

**Comment by DeekshithVelmula** [comment]
@Aserguy
@srinu1015
@sahaanup65
@giridathac
@piscesbangalore
@GTTech2305
@nixnotwin
@ranjeets9
@KEERTHI1988-K2
@Akil0189
@nixnotwin

**Comment by giridathac** [comment]
Working.. Thank you.. 

As mentioned earlier it works after setting up a simple IPTV client (through TV tab in sidebar),  but it doesn't play if you take the addons/languages route. Maybe, you should look at it as well.

**Comment by srinu1015** [comment]
@DeekshithVelmula , it's working thank you.

**Comment by vrmsreddy** [comment]
@DeekshithVelmula  it is working with latest kodi or old version too?

**Comment by vrmsreddy** [comment]
@DeekshithVelmula  it working only with latest kodi
